export interface FacilityType {
  name: string;
  processingTypes: string[];
}

export const facilityTypes: FacilityType[] = [
  {
    name: "Raw Material Processing or Production",
    processingTypes: [
      "Biological Recycling",
      "Boiling",
      "Breeding",
      "Chemical Recycling",
      "Chemical Synthesis",
      "Collecting",
      "Concentrating",
      "Disassembly",
      "Down Processing",
      "Dry Spinning",
      "Extrusion",
      "Ginning",
      "Hatchery",
      "Mechanical Recycling",
      "Melt Spinning",
      "Preparation",
      "Preparatory",
      "Processing Site",
      "Pulp making",
      "Raw Material Processing or Production",
      "Retting",
      "Scouring",
      "Shredding",
      "Slaughterhouse",
      "Slaughtering",
      "Sorting",
      "Spinning",
      "Standardization/ Chemical finishing",
      "Synthetic Leather Production",
      "Tannery",
      "Tanning",
      "Textile Recycling",
      "Top making",
      "Twisting/Texturizing Facility",
      "Wet Spinning",
      "Yarn spinning",
    ],
  },
  {
    name: "Textile or Material Production",
    processingTypes: [
      "Blending",
      "Bonding",
      "Buffing",
      "Components",
      "Doubling",
      "Embellishment",
      "Embossing",
      "Embroidery",
      "Fabric Mill",
      "Flat Knit",
      "Fusing",
      "Garment Accessories Manufacturing",
      "Knitting",
      "Circular Knitting",
      "Lace Knitting",
      "Knitting Seamless",
      "Knitting V Bed",
      "Knitting Warp",
      "Laminating",
      "Material Creation",
      "Material Production",
      "Mill",
      "Non woven manufacturing",
      "Non-woven Processing",
      "Painting",
      "Pressing",
      "Pelletizing",
      "Spraying",
      "Straight bar knitting",
      "Textile or Material Production",
      "Textile Mill",
      "Weaving",
      "Welding",
    ],
  },
  {
    name: "Printing, Product Dyeing and Laundering",
    processingTypes: [
      "Batch Dyeing",
      "Coating",
      "Continuous dyeing",
      "Direct Digital Ink Printing",
      "Dyeing",
      "Fabric All Over Print",
      "Fabric Chemical FInishing",
      "Finishing",
      "Fiber Dye",
      "Flat Screen Printing",
      "Garment Dyeing",
      "Garment Place Print",
      "Garment Wash",
      "Garment Finishing",
      "Hand Dye",
      "Laundering",
      "Laundry",
      "Pre-treatment",
      "Printing",
      "Printing, Product Dyeing and Laundering",
      "Product Dyeing",
      "Rotary Printing",
      "Screen Printing",
      "Spray Dye",
      "Sublimation",
      "Textile Dyeing",
      "Textile Printing",
      "Textile Chemical Finishing",
      "Textile Mechanical Finishing",
      "Tye Dye",
      "Washing",
      "Wet Processing",
      "Wet roller printing",
      "Yarn Dyeing",
    ],
  },
  {
    name: "Final Product Assembly",
    processingTypes: [
      "Assembly",
      "Cutting",
      "Cut & Sew",
      "Embellishment",
      "Embroidery",
      "Final Product Assembly",
      "Finished Goods",
      "Ironing",
      "Knitwear Assembly",
      "Knit Composite",
      "Linking",
      "Manufacturing",
      "Making up",
      "Marker Making",
      "Molding",
      "Packaging",
      "Pattern Grading",
      "Pleating",
      "Pressing",
      "Product Finishing",
      "Ready Made Garment",
      "Sample Making",
      "Seam taping",
      "Sewing",
      "Steaming",
      "Stitching",
      "Tailoring",
    ],
  },
  {
    name: "Office / HQ",
    processingTypes: [
      "Headquarters",
      "No processing",
      "Office",
      "Office / HQ",
      "Sourcing Agent",
      "Trading",
    ],
  },
  {
    name: "Warehousing / Distribution",
    processingTypes: [
      "Packing",
      "Warehousing / Distribution",
    ],
  },
];
